<?php

function front_page_form_menu() {
    $items['front-page-form'] = array(
        'title' => 'Sportal Search',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('front_page_form_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function front_page_form_form($form, &$form_state) {

    $options_first = _front_page_form_activity_type_dropdown();
    $selected = isset($form_state['values']['dropdown_first']) ? $form_state['values']['dropdown_first'] : key($options_first);

    $form['dropdown_first'] = array(
        '#type' => 'select',
        '#title' => 'Activity Type',
        '#options' => $options_first,
        '#default_value' => $selected,
        '#ajax' => array(
            'callback' => 'front_page_form_dropdown_callback',
            'wrapper' => 'dropdown-second-replace',
            'progress' => array('type' => 'none'),
        ),
    );
    $form['dropdown_second'] = array(
        '#type' => 'select',
        '#title' => t("Activity type:") . " " . $options_first[$selected],
        '#prefix' => '<div id="dropdown-second-replace">',
        '#suffix' => '</div>',
        '#options' => front_page_form_sport_dropdown($selected),
        '#default_value' => isset($form_state['values']['dropdown_second']) ? $form_state['values']['dropdown_second'] : '',
    );
    $form['zip'] = array(
        '#type' => 'textfield',
        '#title' => 'Enter Zip code',
        '#placeholder' => t('For ex: 97227'),
        '#element_validate' => array('element_validate_range'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    return $form;
}

function front_page_form_dropdown_callback($form, $form_state) {
    return $form['dropdown_second'];
}

function _front_page_form_activity_type_dropdown() {
    return drupal_map_assoc(
        array(
            t('Pickup Games'),
            t('Leagues'),
            t('Runs and Races'),
            t('Places to Play'),
        )
    );
}

function front_page_form_sport_dropdown($type = '') {
    $options = array(
        t('Pickup Games') => drupal_map_assoc(
            array(
                t('Baseball'),
                t('Basketball'),
                t('Flag Football'),
                t('Kickball'),
                t('Soccer'),
                t('Ultimate Frisbee'),
            )
        ),
        t('Leagues') => drupal_map_assoc(
            array(
                t('Baseball'),
                t('Basketball'),
                t('Flag Football'),
                t('Kickball'),
                t('Soccer'),
                t('Ultimate Frisbee'),
            )
        ),
        t('Runs and Races') => drupal_map_assoc(
            array(
                t('Road Bike Race'),
                t('Mountain Bike Race'),
                t('Triathlon'),
                t('Biathlon'),
                t('Marathon'),
                t('Charity Run'),
                t('Trail Run'),
                t('Obstacle Run'),
            )
        ),
        t('Places to Play') => drupal_map_assoc(
            array(
                t('Multipurpose Field Space'),
                t('Soccer Field'),
                t('Basketball Court'),
                t('Baseball Diamond'),
                t('Football Field'),
                t('Tennis Court'),
                t('Track'),
                t('Volleyball Court'),
                t('Ice Rink'),
                t('Squash Court'),
                t('Yoga Gym'),
                t('Pool'),
                t('Fitness Center'),
                t('Walking/Running Trails'),
                t('Hiking Trails'),
            )
        ),
    );

    if (isset($options[$type])) {
        return $options[$type];
    } else {
        return array();
    }
}

function element_validate_range($element) {
    $zip = intval($element['#value']);
    $zip_code = str_split($zip);

    $zip_numbers = range(0, 9);

    if (strlen($zip) !== 5) {
        form_set_error($zip, t('Zip code must be five numbers.'));
    }

    foreach($zip_code as $zip_num) {
        if (!in_array($zip_num, $zip_numbers)) {
            form_set_error($zip, t('Please only enter numbers 0-9.'));
        }
    }
}

function front_page_form_form_submit($form_id, &$form_state) {
    $first = $form_state['values']['dropdown_first'];
    $second = $form_state['values']['dropdown_second'];
    $zip = $form_state['values']['zip'];

    if($first === "Pickup Games") {
        $form_state['redirect'] = 'pickup';
    } elseif($first === "Leagues") {

        $url = 'leagues?field_league_sport='. $second . '&field_age_group_value=All&field_geofield_distance%5Bdistance%5D=25&field_geofield_distance%5Bunit%5D=3959&field_geofield_distance%5Borigin%5D=' . $zip;

        $form_state['redirect'] = $url;

    } elseif($first === "Runs and Races") {
        $form_state['redirect'] = 'runs-and-races';
    } elseif($first === "Places to Play") {
        $form_state['redirect'] = 'find-a-place-to-play';
    }
}
